---
version: 2
builds:
  - id: default
    env:
      - CGO_ENABLED=0
  - id: with-certs
    env:
      - CGO_ENABLED=0
    tags:
      - certs
archives:
  - formats:
      - binary
    ids:
      - default
    name_template: >-
      {{ .ProjectName }}_
      {{- if eq .Os "linux" }}Linux
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
dockers_v2:
  - images:
      - 'ghcr.io/arnested/{{ .ProjectName }}'
    tags:
      - '{{ .Tag }}'
      - 'v{{ .Major }}'
      - 'latest'
    ids:
      - with-certs
    labels:
      "org.opencontainers.image.created": "{{.CommitDate}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.source": "https://github.com/arnested/{{.ProjectName}}"
      "org.opencontainers.image.title": "{{.ProjectName}}"
      "org.opencontainers.image.version": "{{.Version}}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  prerelease: auto
