---
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
archives:
  - format: binary
    name_template: >-
      {{ .ProjectName }}_
      {{- if eq .Os "linux" }}Linux
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
dockers:
  - image_templates:
      - 'ghcr.io/arnested/{{ .ProjectName }}:{{ .Tag }}'
      - 'ghcr.io/arnested/{{ .ProjectName }}:v{{ .Major }}'
      - 'ghcr.io/arnested/{{ .ProjectName }}:latest'
    goos: linux
    goarch: amd64
    skip_push: auto
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.CommitDate}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.source=https://github.com/arnested/{{.ProjectName}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  prerelease: auto
